import type { components } from "../../generated/aster-protocol";

export type LoginPasswordRequest = components["schemas"]["LoginPasswordRequest"];
export type RefreshSessionRequest = components["schemas"]["RefreshSessionRequest"];
export type LogoutRequest = components["schemas"]["LogoutRequest"];
export type GoogleAuthorizationRequest = components["schemas"]["GoogleAuthorizationRequest"];
export type GoogleAuthorizationResponse = components["schemas"]["GoogleAuthorizationResponse"];
export type GoogleExchangeRequest = components["schemas"]["GoogleExchangeRequest"];
export type SessionTokenResponse = components["schemas"]["SessionTokenResponse"];
export type UserSelf = components["schemas"]["UserSelf"];
export type ApiErrorBody = components["schemas"]["Error"];
export type Guild = components["schemas"]["Guild"];
export type GuildList = components["schemas"]["GuildList"];
export type Channel = components["schemas"]["Channel"];
export type ChannelList = components["schemas"]["ChannelList"];
export type GuildMember = components["schemas"]["GuildMember"];
export type GuildMemberList = components["schemas"]["GuildMemberList"];
export type Role = components["schemas"]["Role"];
export type RoleList = components["schemas"]["RoleList"];
export type Presence = components["schemas"]["Presence"];
export type UpdatePresenceRequest = components["schemas"]["UpdatePresenceRequest"];
export type ReadState = components["schemas"]["ReadState"];
export type ReadStateList = components["schemas"]["ReadStateList"];
export type UpdateReadStateRequest = components["schemas"]["UpdateReadStateRequest"];
export type Message = components["schemas"]["Message"];
export type MessageReaction = components["schemas"]["MessageReaction"];
export type MessageList = components["schemas"]["MessageList"];
export type CreateMessageRequest = components["schemas"]["CreateMessageRequest"];
export type UpdateMessageRequest = components["schemas"]["UpdateMessageRequest"];
export type Attachment = components["schemas"]["Attachment"];
export type AttachmentUploadIntent = components["schemas"]["AttachmentUploadIntent"];
export type AttachmentDownloadIntent = components["schemas"]["AttachmentDownloadIntent"];
export type CreateAttachmentUploadIntentRequest = components["schemas"]["CreateAttachmentUploadIntentRequest"];
export type VoiceSession = components["schemas"]["VoiceSession"];
export type VoiceState = components["schemas"]["VoiceState"];
export type VoiceStateList = components["schemas"]["VoiceStateList"];
export type JoinVoiceChannelRequest = components["schemas"]["JoinVoiceChannelRequest"];
export type UpdateVoiceStateRequest = components["schemas"]["UpdateVoiceStateRequest"];
export type DirectChannelList = components["schemas"]["ChannelList"];
export type ThreadList = components["schemas"]["ChannelList"];
export type MessageSearchResult = components["schemas"]["MessageSearchResult"];

export type AuthStatus = "checking" | "authenticated" | "unauthenticated";
export type GoogleAuthStatus = "idle" | "opening" | "waiting" | "exchanging";

export type AuthContextValue = {
  status: AuthStatus;
  user: UserSelf | null;
  error: string | null;
  accessToken: string | null;
  googleStatus: GoogleAuthStatus;
  loginWithPassword: (request: LoginPasswordRequest) => Promise<void>;
  loginWithGoogle: () => Promise<void>;
  logout: () => Promise<void>;
  retrySession: () => Promise<void>;
  enterDemo: () => void;
};
